version: "3"
services:
  grader:
    container_name: benchmark-grader
    build:
      context: .
      dockerfile: Dockerfile.grader
    restart: always
    volumes:
      - ./dataset:/dataset

    networks:
          - bench

  solution:
    container_name: solution-app
    build:
      context: .
      dockerfile: Dockerfile.solution
    depends_on:
      - grader

    networks:
          - bench


networks:
    bench: {}
