version: "3"
services:
  grader:
    container_name: benchmark-grader
    build:
      context: .
      dockerfile: Dockerfile.grader
    environment: 
      HARD_TIMEOUT_SECONDS: 7200
      DATASET_PATH: "/dataset"
      RESULT_FILE_PATH: '/dataset'
    volumes:
      - ./dataset:/dataset
    networks:
      - bench

  solution:
    container_name: solution-app
    build:
      context: .
      dockerfile: Dockerfile.solution
    environment:
      BENCHMARK_SYSTEM_URL: "grader"
    depends_on:
      - grader
    networks:
      - bench

networks:
  bench: {}
