FROM ubuntu:18.04

COPY grader_app/requirements.txt /

# install your dependencies
RUN apt-get update && apt-get install -y build-essential

RUN apt-get update && apt-get install -y \
    python3-pip

RUN python3 -V
RUN pip3 install --no-cache-dir -r /requirements.txt

COPY grader_app/ /app
WORKDIR /app

RUN python3 createTables.py

CMD ["python3", "grader.py"]
