version: "3"
services:
  grader:
    container_name: benchmark-grader
    build:
      context: .
      dockerfile: Dockerfile.grader
    restart: always
    volumes:
      - ./dataset:/dataset
    ports:
      - 8080:80

    networks:
          - bench

  solution:
    container_name: solution-app
    build:
      context: .
      dockerfile: Dockerfile.solution
    environment:
      BENCHMARK_SYSTEM_URL: 'grader'
    depends_on:
      - grader
    command: ["/wait-for-it.sh", "grader:80","-t","4000","--","python3","solution.py"]
    
    networks:
          - bench


networks:
    bench: {}
