FROM ubuntu:18.04

RUN apt-get update && apt-get install -y \
    build-essential \
    python3-pip

RUN python3 -V

COPY grader_app/requirements.txt /

RUN pip3 install --no-cache-dir -r requirements.txt

COPY grader_app/ /app
WORKDIR /app

CMD ["python3", "-u", "grader.py"]