version: "3"
services:
  grader:
    container_name: benchmark-grader
    build:
      context: .
      dockerfile: Dockerfile.grader
    environment: 
      HARD_TIMEOUT_SECONDS: 7200
      DATASET_PATH: "./dataset"
    volumes:
      - ../dataset:/dataset
    networks:
      - bench

  solution:
    container_name: solution-app
    build:
      context: .
      dockerfile: Dockerfile.solution
    environment:
      BENCHMARK_SYSTEM_URL: "grader"
    depends_on:
      - grader
    command:
      [
        "/wait-for-it.sh",
        "grader:80",
        "-t",
        "1200",
        "--",
        "python3",
        "-u",
        "solution.py",
      ]
    networks:
      - bench

networks:
  bench: {}
