FROM ubuntu:18.04

# install your dependencies
RUN apt-get update && apt-get install -y build-essential

RUN apt-get update && apt-get install -y \
    python3-pip

RUN python3 -V

COPY dataset /dataset
COPY grader_app/ /app
WORKDIR /app

RUN pip3 install --no-cache-dir -r requirements.txt

CMD ["python3", "grader.py"]