version: "3"
services:
  grader:
    container_name: benchmark-grader-test
    build:
      context: .
      dockerfile: Dockerfile.grader
    environment:
      HARD_TIMEOUT_SECONDS: 18000
      DATASET_PATH: "/dataset"
      RESULTS_PATH: "/dataset"
      GRADER_CACHE_ENABLED: "True"
    volumes:
      - ./dataset:/dataset
    networks:
      - bench-test

  solution:
    container_name: solution-app-test
    build:
      context: .
      dockerfile: Dockerfile.solution
    environment:
      BENCHMARK_SYSTEM_URL: "grader"
    depends_on:
      - grader
    networks:
      - bench-test

networks:
  bench-test: {}
