DATABASE_NAME = 'gc.db'
BENCHMARK_ENDPOINT = '/data/'
GRADER_ENDPOINT = '/grade/'
RESULTS_EXPORTER_ENDPOINT = '/export/'
SERVER_PORT = 80
SERVER_HOST = '0.0.0.0'
INPUT_BATCH_SIZE = 1000
INPUT_FILE = '../dataset/in.csv'
OUTPUT_FILE = '../dataset/out.csv'

